[[agents]]
id = "agent-1"
keystore_file = "keystores/agent1/<AGENT_1_PUB_KEY>.keystore"
name = "Agent 1"
public_address = "<AGENT_1_PUB_KEY>"

[[dnas]]
file = "dna_src/dist/dna_src.dna.json"
hash = "<DNA_HASH>"
id = "rad-tool-dna"

[[instances]]
agent = "agent-1"
dna = "rad-tool-dna"
id = "rad-tool-1"

[instances.storage]
path = ".holochain/holo/storage/agent-1/rad-tool-dna"
type = "file"

[[interfaces]]
id = "websocket-interface"

[interfaces.driver]
port = 3400
type = "websocket"

[[interfaces.instances]]
id = "rad-tool-1"

[[interfaces]]
admin = true
id = "http-interface"

[interfaces.driver]
port = 3300
type = "http"

[[interfaces.instances]]
id = "rad-tool-1"

[logger]
type = "debug"

[logger.rules]

[[logger.rules.rules]]
color = "red"
exclude = false
pattern = "^err/"

[[logger.rules.rules]]
color = "white"
exclude = false
pattern = "^debug/dna"

[network]
sim2h_url = "ws://public.sim2h.net:9000"
type = "sim2h"

bridges = []
persistence_dir = ".holochain/holo"
